// import React from "react";
// import { useLocation } from "react-router-dom";
// import Navbar from "../components/Navbar";

// const GenerateBill = () => {
//   const location = useLocation();
//   const { farmer, shopkeeper } = location.state || {};

//   if (!farmer || !shopkeeper) {
//     return (
//       <div className="container">
//         <Navbar />
//         <h2 className="mt-4">Error: No farmer or shopkeeper data found.</h2>
//       </div>
//     );
//   }

//   // Get the shopkeeper's surname (shop name)
//   const shopName = shopkeeper.lastName ? `${shopkeeper.lastName} Trading Co.🚚` : "Default Trading Co.";

//   return (
//     <div className="container">
//       <Navbar />
//       <h2 className="mt-4">Generate Bill</h2>
//       <div className="card p-4 shadow mt-3">
//         {/* Bill Header */}
//         <div className="text-center">
//           <h3>{shopName}</h3>
//           <p>============================================</p>
//         </div>

//         {/* Shopkeeper and Farmer Details */}
//         <div className="mt-3">
//           <h4>Shopkeeper Details</h4>
//           <p>
//             <strong>Name:</strong> {shopkeeper.firstName} {shopkeeper.lastName}
//           </p>
//           <p>
//             <strong>Email:</strong> {shopkeeper.email}
//           </p>
//           <p>
//             <strong>Contact No:</strong> {shopkeeper.contactNo}
//           </p>

//           <h4>Farmer Details</h4>
//           <p>
//             <strong>Name:</strong> {farmer.firstName} {farmer.lastName}
//           </p>
//           <p>
//             <strong>Email:</strong> {farmer.email}
//           </p>
//           <p>
//             <strong>Contact No:</strong> {farmer.contactNo}
//           </p>
//         </div>

//         {/* Bill Details */}
//         <table className="table table-bordered mt-3">
//           <thead>
//             <tr>
//               <th>Project</th>
//               <th>Unit</th>
//               <th>Rating</th>
//             </tr>
//           </thead>
//           <tbody>
//             <tr>
//               <td>410</td>
//               <td>411</td>
//               <td>14/02/2025</td>
//             </tr>
//           </tbody>
//         </table>

//         {/* Item Details */}
//         <table className="table table-bordered mt-3">
//           <thead>
//             <tr>
//               <th>Item Qty.</th>
//               <th>Description of Goods</th>
//               <th>Net Weight</th>
//               <th>Rate</th>
//               <th>Grand Total</th>
//               <th>Details</th>
//               <th>Inclusive Rs.</th>
//               <th>Unit Price</th>
//             </tr>
//           </thead>
//           <tbody>
//             <tr>
//               <td>1</td>
//               <td>Item Description</td>
//               <td>26.00 kg</td>
//               <td>240.00</td>
//               <td>624.00</td>
//               <td>
//                 <p>Includes Hamali</p>
//                 <p>Additional Charges</p>
//               </td>
//               <td>5.90 Rs.</td>
//               <td>50.00 Rs.</td>
//             </tr>
//           </tbody>
//         </table>

//         {/* Summary Section */}
//         <div className="mt-3">
//           <p>
//             <strong>Total Rs.:</strong> 624.00
//           </p>
//           <p>
//             <strong>Total Exp.:</strong> 0.00 Rs.
//           </p>
//           <p>
//             <strong>Net Rs.:</strong> 564.00
//           </p>
//           <p>
//             <strong>Balance Rs.:</strong> 564.00
//           </p>
//         </div>

//         {/* Footer */}
//         <div className="text-center mt-3">
//           <p>
//             Invoice generated by {shopkeeper.firstName} {shopkeeper.lastName}
//           </p>
//           <p>Created on: {new Date().toLocaleDateString()}</p>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default GenerateBill;



import React from "react";
import { useLocation } from "react-router-dom";
import Navbar from "../components/Navbar";

const GenerateBill = () => {
  const location = useLocation();
  const { farmer, shopkeeper } = location.state || {};

  if (!farmer || !shopkeeper) {
    return (
      <div className="container">
        <Navbar />
        <h2 className="mt-4">Error: No farmer or shopkeeper data found.</h2>
      </div>
    );
  }

  const shopName = shopkeeper.lastName ? `Shri ${shopkeeper.lastName} Trading Co.` : "Default Trading Co.";

  return (
    <div className="container border p-4">
      <Navbar />
      <div className="text-center">
        <h5>Agriculture produce Market Committee</h5>
        <h3>{shopName}</h3>
        <p>Onion, Potato, Garlic & Vegetables dealers</p>
        <p>Shri Chhatrapati Shivaji Market Yard, Pune - 411037</p>
        <p>PROP: {shopkeeper.firstName} {shopkeeper.lastName} | Mobile: {shopkeeper.contactNo}</p>
      </div>

      <div className="d-flex justify-content-between mt-4 border p-2">
        <div>
          <p>Shop No.</p>
          <div className="border p-2" style={{ width: "100px", height: "50px" }}></div>
        </div>
        <div>
          <p>Calculation Strip No: (bill id)</p>
          <p>Date: {new Date().toLocaleDateString()}</p>
        </div>
        <div>
          <p>Name of the Farmer: {farmer.firstName} {farmer.lastName}</p>
          <p>Transport: (Enter Name here)</p>
        </div>
      </div>

      <table className="table table-bordered mt-3 text-center">
        <thead>
          <tr>
            <th>Qty</th>
            <th>Types of goods</th>
            <th>Net Weight</th>
            <th>Per 10KG Rate</th>
            <th>Total</th>
            <th>Details of Expense</th>
            <th>Money RS.</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><input type="text" placeholder="Enter qty" /></td>
            <td><input type="text" placeholder="Enter goods" /></td>
            <td><input type="text" placeholder="Enter weight" /></td>
            <td><input type="text" /></td>
            <td><input type="text" /></td>
            <td>
              <p>Hamali</p>
              <p>Borai</p>
              <p>Tolai</p>
              <p>Mapai</p>
              <p>Motor fare</p>
            </td>
            <td>
              <input type="text" />
              <input type="text" />
              <input type="text" />
              <input type="text" />
              <input type="text" />
            </td>
          </tr>
        </tbody>
      </table>

      <div className="d-flex justify-content-between">
        <p>Total RS.: <input type="text" /></p>
        <p>Total Exp.: <input type="text" /></p>
      </div>
      <div className="d-flex justify-content-between">
        <p>Net RS.: <input type="text" /></p>
        <p>Less Expense: <input type="text" /></p>
      </div>
      <div className="d-flex justify-content-between">
        <p>Balance: <input type="text" /></p>
        <p>Yours Truly: {shopkeeper.firstName} {shopkeeper.lastName}</p>
      </div>

      <div className="text-center mt-4">
        <p>Cash Received</p>
      </div>
    </div>
  );
};

export default GenerateBill;
